services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3001:3000"
    volumes:
      - ./data/oneapi:/data
      - ./logs:/app/logs
      - ./web/air:/app/web/build
    environment:
      - SQL_DSN=oneapi:123456@tcp(mysql:3306)/one-api
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=techdou_test_secret_2024
      - TZ=Asia/Shanghai
      - SYSTEM_NAME=WALANKA
      - SERVER_ADDRESS=http://walankaai.com
      - ALIPAY_APP_ID=2088480387025401
      - ALIPAY_PRIVATE_KEY=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCeUM6NWwHSQRQiRqoN5H8X6PH7+uDYoPuapqf9CXogtGc9H1lOp3jr6mg4bqmKOxuEr6EyZKP4eQqjrR6TagPA9bYjv1VDGP2StC59L0k5PKwEWWuPoaZKXM2C69VI6nQFlIc5o9wgcCnzRNBWnV7mm061L/SJ1s8GR++pKa9YQJRYsGc7Q/dWe+3KjDTzDvz0ZZ5L0cT5flKnEBMAEzyF3wbLjDvh/bwAlKBaYhxCrOXN4J+R7/PGIOtDuyo2oc56FVD7zb7TcTwyoI1oXLXX9HT7c0OL8QBgMJ08Om4l2FoNZd3VNgaVR5xu2kFX7tK83M8+Ff6BFtZL0QuVpAtTAgMBAAECggEAGjPnq++3InSQ/4dQmBIMkwmEG5+PXWtvmU4iGbha1VTmjXBF2MXRNsLKUyTFvNJBoLls5alQlkx6XVLG78EpM+O3LL17QCq/tWtLEn8kEGwhUGr4aYJowoAPp66e032yjEXkB78+LMRDvTbTgLJ1RZfI9CYmxDWgeDqpyQbUNbffSbTxhTXneGpuh5XjY4+5V1uzUU8/130WkJ97qEl9V6s4AfpIBqZuafrKjDZz+8teO5vnqDYkttMS75Fn74nnVyLOJQGZwlF19gZzmYOFBPpUrqrDIhELtBipGZgJm59VzDTeGGt14RC7jBaUDgcZgrY/gJkI2vrPWBF67wOr8QKBgQDnnWT+pevZjtyduc/SRASEvJT8KLCSemX7kVpyp1vCGVvBn0xngosbnU66lNJHywFZ6x6t5CEZBXxBaYf6fozbQQqcZOLa9kcIfYlE+3gisdvZuVgp2BQV70FydzBXfHhoar2LOM6elCdxVbybumM48ubN6I8xgPDoypbsHEJ/KQKBgQCu+9BxJZtpCSoilfosahmHgnC5/2JnOi6MJYtr0O/Mhyss4f5oVEAGQ3pHgNv8WOjigIDerWlZLw29o3AEk+fBzSiBwealv35DG3xl/4vwwyD+K4hmvYL0R4eN1zV8ad2oDuxVaaYPUrMqHHDKNMzqZAixMFGX6+4UhSYiAunSGwKBgBx4hImo66z6mrPou1slcUi/xbCZb9sRoKej3nJpkCXz6AuNAV9X9LGYTK0yzgZ1Nd1PwZ2uhUMGIZgI2OY52Ca7gAppfFleHK02gUExiDr7kgLZfbTnEtD/cBQaAp8+da6gMFyExyFHJPIRj/W0m63MbgKxq6hyKSr0fEjZ0HLBAoGAGHnSozD+dwe4JBRUZQgGQCUnvWySiBvkTOgng1I7aKFzkZie7Fr0havEm+HTY43QLXaKEBuzg60IQAFvdsR1g289/kBwEbkiYSKkGORQ38F7iPHv52cUvTSQKm/y5E8umQZVWnEnsDcCJp7JzA7sptCNQrOehiCTMb2aIuHDcQcCgYBfPA8AegGMqWEFba7qEECdMofHmyzu7QsYYbcfrFSOdNRdYkfD2bFfeYlEBUeRdTDwlgbQ9g+WvF6tmLvUVLAKOHDtwXhET6qr7sKwzwjEh1AZBh+m3klwfdx4zv/CP4t6P8DE5sA8bfk1kESPmq8GIGEfxg+cvloLFa05ZTheTw==
      - ALIPAY_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnlDOjVsB0kEUIkaqDeR/F+jx+/rg2KD7mqan/Ql6ILRnPR9ZTqd46+poOG6pijsbhK+hMmSj+HkKo60ek2oDwPW2I79VQxj9krQufS9JOTysBFlrj6GmSlzNguvVSOp0BZSHOaPcIHAp80TQVp1e5ptOtS/0idbPBkfvqSmvWECUWLBnO0P3Vnvtyow08w789GWeS9HE+X5SpxATABM8hd8Gy4w74f28AJSgWmIcQqzlzeCfke/zxiDrQ7sqNqHOehVQ+82+03E8MqCNaFy11/R0+3NDi/EAYDCdPDpuJdhaDWXd1TYGlUecbtpBV+7SvNzPPhX+gRbWS9ELlaQLUwIDAQAB
      - PAY_RATE_RMB=7.2
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "${REGISTRY:-docker.io}/redis:latest"
    container_name: redis
    restart: always

  mysql:
    image: "${REGISTRY:-docker.io}/mysql:8.2.0"
    restart: always
    container_name: mysql
    volumes:
       - ./data/mysql:/var/lib/mysql
    ports:
       - '33088:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'TechDou@2024'
      MYSQL_USER: oneapi
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: one-api
